<a class="twitter-timeline"  
	data-widget-id="<?php echo $this->id; ?>"
	width="<?php echo $this->width; ?>"
	height="<?php echo $this->height; ?>"
	data-theme="<?php echo $this->theme; ?>" 
	data-link-color="<?php echo $this->linkColor; ?>"
	data-border-color=<?php echo $this->borderColor; ?>
	data-chrome="<?php echo $this->chrome; ?>"
	data-tweet-limit="<?php echo $this->tweetLimit; ?>"
	lang="<?php echo $this->lang; ?>"></a>